server:
  port: 8080

spring:
  application:
    name: paycontrol
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/paycontrol?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: usr_paycontrol
    password: paycontrol